# code:language=ansible
---
- name: Removing all the files
  tags:
    - never
    - purge_all
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ nginx_sites_enabled }}"
    - "{{ nginx_sites_available }}"
    - "{{ nginx_letsencrypt }}"

- name: Removing the selected files
  tags:
    - never
    - purge
  ansible.builtin.file:
    path: "{{ item.0 }}/{{ item.1.subdomain }}"
    state: absent
  loop: "{{ query('ansible.builtin.cartesian', nginx_paths, proxy_domains) }}"
  vars:
    nginx_paths:
      - "{{ nginx_sites_enabled }}"
      - "{{ nginx_sites_available }}"
      - "{{ nginx_letsencrypt }}"
