# code:language=ansible
---
- name: Installing and configuring NGINX
  tags:
    - never
    - install
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
          - ufw
        state: present
        update_cache: true

    - name: Making requried folders if doesn't exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0644'
      loop:
        - "{{ nginx_sites_enabled }}"
        - "{{ nginx_sites_available }}"
        - "{{ nginx_letsencrypt }}"

    - name: Templating Nginx configuration for each subdomain
      ansible.builtin.template:
        src: nginx_vhost.conf.j2
        dest: "{{ nginx_sites_available }}/{{ item.subdomain }}"
        mode: '0644'
      loop: "{{ proxy_domains }}"

    - name: Enable Nginx configuration
      ansible.builtin.file:
        src: "{{ nginx_sites_available }}/{{ item.subdomain }}"
        dest: "{{ nginx_sites_enabled }}/{{ item.subdomain }}"
        state: link
      loop: "{{ proxy_domains }}"

    - name: Allow HTTP and HTTPS and SSH traffic (UFW)
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - "80"
        - "443"
        - "22"

    - name: Obtain SSL certificates for all subdomains
      ansible.builtin.command: certbot \
        --nginx -d {{ item.subdomain }} \
        --non-interactive \
        --agree-tos -m {{ nginx_email }} \
        --redirect --cert-name {{ item.subdomain }}
      args:
        creates: "{{ nginx_letsencrypt }}/{{ item.subdomain }}/fullchain.pem"
      loop: "{{ proxy_domains }}"
      notify: Restart Nginx

    - name: Set up automatic SSL renewal
      ansible.builtin.cron:
        name: "Renew Let's Encrypt certificates"
        job: "certbot renew --quiet"
        minute: "0"
        hour: "3"
        month: "1,4,7,10"
